### ISSUE TITLE
Issue with non ASCII characters in video details if default charset is not utf-8

### ISSUE THREAD

**Issue by maciejbudzyn** [sealedtx/java-youtube-downloader#10]
Hi,

With default Parser and default Extractor, the InputStreamReader that reads from HttpURLConnection inputstream uses default character encoding. In my case it was not a utf-8 what results in missing non ASCII characters in video details.

The simple solution is to explicitly specify the utf-8 charset: 
```
BufferedReader in = new BufferedReader(new InputStreamReader(
                        connection.getInputStream(), StandardCharsets.UTF_8));
```

What I can also suggest is to use dependency injection to inject extractor in default parser, it would make life easier when man needs to alter just a default extractor and use derived version with default parser.

**Comment by sealedtx** [comment]
@maciejbudzyn Thank you for fix suggestion, I will include it in the next release. About DI: I understand that it would be easier but I want to keep this repo as simple as possible with no additional dependencies. I will think about it

**Comment by sealedtx** [comment]
resolved in https://github.com/sealedtx/java-youtube-downloader/commit/eb58ed2b4072b256693c8c55b7fc2a7cc1dc3d06
