### ISSUE TITLE
How to Know The Size Of Video ?

### ISSUE THREAD

**Issue by Shazyar-taha** [sealedtx/java-youtube-downloader#100]
I have a video and I want to show me a list of video details 
Like this
1080p = 313.1 MB
720p = 162.2 MB
....

**Comment by sealedtx** [comment]
@Shazyar-taha Hi, you can use
https://github.com/sealedtx/java-youtube-downloader/blob/b84d42f931c0f34a748567dadb0682b23b44c14b/src/main/java/com/github/kiulian/downloader/model/videos/formats/VideoFormat.java#L12 qualityLabel (1080p)

https://github.com/sealedtx/java-youtube-downloader/blob/b84d42f931c0f34a748567dadb0682b23b44c14b/src/main/java/com/github/kiulian/downloader/model/videos/formats/Format.java#L22 contentLength in bytes for getting video size (313 MB)

**Comment by Shazyar-taha** [comment]
thank you so much bro
