### ISSUE TITLE
It seems like maven artifacts are gone causing dependency issues.

### ISSUE THREAD

**Issue by dk8996** [sealedtx/java-youtube-downloader#109]
It seems like the projects Maven artifacts got removed from (https://repository.mulesoft.org/nexus/content/repositories/public/com/github/sealedtx/java-youtube-downloader/)

**Comment by sealedtx** [comment]
@dk8996 have a look at https://github.com/jitpack/jitpack.io/issues/5337
seems like jitpack.io is down

**Comment by sealedtx** [comment]
jitpack is up now
