### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by zyk-miao** [sealedtx/java-youtube-downloader#110]
YoutubeDownloader downloader = new YoutubeDownloader();
        RequestSearchResult request = new RequestSearchResult("where is your love")
                .type(TypeField.VIDEO).forceExactQuery(true);
        List<SearchResultItem> items = downloader.search(request).data().items();

it will throw "NumberFormatException: For input string: "4182383014""

**Comment by sealedtx** [comment]
@zyk-miao hi, do you want to submit pull request with fix?

**Comment by zyk-miao** [comment]
Maybe I can try

**Comment by sealedtx** [comment]
great, appreciate it
