### ISSUE TITLE
Get video fragment of defined duration between two seconds/minutes

### ISSUE THREAD

**Issue by mohasaid** [sealedtx/java-youtube-downloader#13]
Have you considered a method to return a fragment of the video from a second to another second. So if the video has 15 min of duration, and I want only the fragment between the time from 1:30 min to 2:45 min, have a method to get this fragment instead of the whole video.

**Comment by sealedtx** [comment]
@mohasaid Hi, this project doesnt provide any videoprocessing, it just parse youtube video urls. If you know how to do this via youtube link, please share.
