### ISSUE TITLE
Video quality options are missing

### ISSUE THREAD

**Issue by LivingCodeX** [sealedtx/java-youtube-downloader#16]
There's a video which is available in 1080p but I can only download it in 360p with this tool. How can I fix that and why is YouTube hiding the more high quality options?

**Comment by sealedtx** [comment]
@LivingCodeX, please provide youtube link, so I can test it and find a fix

**Comment by LivingCodeX** [comment]
Video-ID: hONHNdh5dgQ
Link: https://www.youtube.com/watch?v=hONHNdh5dgQ

**Comment by sealedtx** [comment]
@LivingCodeX, hi, I think the problem is that you are looking for video with audio. But youtube usually provide 1-2 url for video with audio with limited quality. You can download better quality by separate video url and audio url and combine them with external tools. Try this code snippet:
```
YoutubeVideo ytVideo = new YoutubeDownloader().getVideo("hONHNdh5dgQ");

System.out.println("Video with audio:"); // I suppose you only looked here
ytVideo.videoWithAudioFormats().forEach(it -> System.out.printf("%s(%s): %s\n", it.videoQuality(), it.qualityLabel(), it.url()));
System.out.println("Video:"); // But if you need higher quality you need these
ytVideo.videoFormats().forEach(it -> System.out.printf("%s(%s): %s\n", it.videoQuality(), it.qualityLabel(), it.url()));
System.out.println("Audio:"); 
ytVideo.audioFormats().forEach(it -> System.out.printf("%s: %s\n", it.audioQuality(), it.url()));
```
