### ISSUE TITLE
Video with audio just downloadable in low resolution

### ISSUE THREAD

**Issue by crcer** [sealedtx/java-youtube-downloader#17]
I am trying to download Videos in higher resolution like Full HD or 4k, but unfortunately I am just able to download in a resolution of 720p.

**Comment by sealedtx** [comment]
@crcer , please provide youtube link, so I can test it and find a fix

**Comment by crcer** [comment]
Alright thank you.
Do you have any recommendation for combining video and audio?

**Comment by sealedtx** [comment]
@crcer I worked with ffmpeg, but to say truth it is not the easiest solution
