### ISSUE TITLE
Wrong key of the "cipher" field 

### ISSUE THREAD

**Issue by AlieksieievYurii** [sealedtx/java-youtube-downloader#20]
Hello, 

I am using currently your library to download videos(audio from video) from YouTube. It was working fine, before some time. Now, when I am trying to get audio formats by calling the function **audioFormats** on the instance of YouTubeVideo class, it returns null. I have dug into the problem and figured out the problem is in the DefaultParser. The function **parseFormat** checks whether given JSON object contains **cipher** keyword, if it is true, the parser retrieves it and then does necessary steps.
So, the problem is with the **cipher** field in the json. Now, this field is called **signatureCipher**.
I guess YouTube has changed a response structure again. By the way, I have created a custom parser and fix this error and it works fine. But, I prefer to use your default parser rather than creating my own, which is actually the same. 

So, I hope you fix the issue as soon as possible:)

**Comment by sealedtx** [comment]
@AlieksieievYurii Thanks a lot for reporting an issue and dugging into the problem! #21 resolved this bug and I already drafted new release with this fix, enjoy it.
