### ISSUE TITLE
Please How Can i extract only Thumbnail

### ISSUE THREAD

**Issue by oluwabajio** [sealedtx/java-youtube-downloader#26]
Please Is there a way i can get the video thumbnail

**Comment by oluwabajio** [comment]
Ok, Found It!!!

This is really a great library.Thanks for providing this.

            // filtering only audio formats
            List<AudioFormat> audioFormats = video.audioFormats();
            audioFormats.forEach(it -> {
                System.out.println(it.audioQuality() + " Audio: " + it.url());
            });

**Comment by oluwabajio** [comment]
Please Is there a way i can get the video thumbnail

**Comment by sealedtx** [comment]
@oluwabajio Hi, here is code snippet:
```
String videoId = "your_id";
YoutubeVideo video = new YoutubeDownloader().getVideo(videoId);
VideoDetails details = video.details();
List<String> thumbnails = details.thumbnails(); // <--- here are thumbnails
```
Please, next time make sure you have searched through README and public methods before opening an issue

**Comment by oluwabajio** [comment]
Got it. Thanks.
