### ISSUE TITLE
Use hardcoded UTF-8 instead of StandardCharsets.UTF_8

### ISSUE THREAD

**Issue by 8o8aua** [sealedtx/java-youtube-downloader#28]
Can't use this library for android application with Android OS  API level < 19 (4.4 (Kitkat))  as StandardCharsets class has been added for 19+ API level only. 

Thank you.

**Comment by sealedtx** [comment]
@8o8aua Hi, is this the only one change needed to support android < 19?

**Comment by 8o8aua** [comment]
I think yes.
But I haven't tried to find anywhere else. I think you should find StandardCharsets.UTF-8 and replace with hardcoded UTF-8 everywhere in your code to avoid ClassNotFoundException in a future

**Comment by sealedtx** [comment]
@8o8aua check out new release

**Comment by 8o8aua** [comment]
Thanks :)
