### ISSUE TITLE
Add a way to get subtitles and pass them to java (it doesn't matter if they have timing)

### ISSUE THREAD

**Issue by Dreaming-Codes** [sealedtx/java-youtube-downloader#31]
Add a way to get subtitles and pass them to java (it doesn't matter if they have timing)

**Comment by sealedtx** [comment]
@Dreaming-Codes Do you know how youtube provides subtitles?

**Comment by Dreaming-Codes** [comment]
Nope but you can read how YouTube DL do

Il mar 21 lug 2020, 12:46 Igor Kiulian <notifications@github.com> ha
scritto:

**Comment by xibr** [comment]
@sealedtx check this [YoutubeStreamExtractor.java](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java) , It may help you to know how subtitles are extracted from YouTube.
