### ISSUE TITLE
Check related to cipher in method  parseFormat in DefaultParser should be changed to signatureCipher

### ISSUE THREAD

**Issue by mohammadnaushad** [sealedtx/java-youtube-downloader#32]
Hi,

First of all I would like to appreciate the tremendous work which you have done here.
Now, I tried running the app on my local and found that in the method parseFormat(JSONObject json, JSONObject config)  you have a check for "cipher" which should be replaced with "signatureCipher" imo. Do let me know if this is a valid bug.
Also, you you have anything in pipeline related to downloading videos from playlist. As of now, whenever I try to download something from playlist, it throws me an error.
I will try to contribute related to playlist if you dont have it in the pipeline. Happy to help

Thanks

**Comment by sealedtx** [comment]
@mohammadnaushad Hi, please check latest version - 2.2.2 (07.21.2020). 
"signatureCipher" problem has been fixed in #21 and merged few releases ago. But if you have errors using latests release, please, share your code snippet and error stacktrace, so you problem can be disscussed and investigated

**Comment by mohammadnaushad** [comment]
I was working on master. I guess the master is not updated. Its working in release 2.2.2 . So, I am closing this issue.
