### ISSUE TITLE
Playlist Support

### ISSUE THREAD

**Issue by mohammadnaushad** [sealedtx/java-youtube-downloader#33]
Do you have any plans for playlist support?

**Comment by sealedtx** [comment]
@mohammadnaushad what exactly do you mean by "playlist support"?

**Comment by naushad3210** [comment]
I meant .. if I pass a url which belongs to a playlist like  https://youtu.be/HdGp3-R6LEc?list=PLFRPNUj0az6RFv9HH7UgLIAGmXSfQXHxH
I should be able to download the video or should be able to fetch all the video details in the playlist. Like all the video links in that playlist so that one can then send the link to download the video

**Comment by sealedtx** [comment]
@naushad3210 I don't have spare time to implement this feature, probably for next few weeks. But PRs are welcomed

**Comment by Grodou** [comment]
Hello,

I found 2 options, both use the `window["ytInitialData"]` JSON section.
(Document and JSON sizes from an actual test suggested by @naushad3210)

1. Use the watch page
- `https://www.youtube.com/watch?v=<video_id>&list=<playlist_id>`
- Document size: 566.12 ko
- JSON size: 310.8 ko
- 5 steps hierarchy `contents.twoColumnWatchNextResults.playlist.playlist.contents[]`

2. Use the playlist page
- `https://www.youtube.com/playlist?list=<playlist_id>`
- Document size: 161.35 ko
- JSON size: 140.2 ko
- 14 steps hierarchy `contents.twoColumnBrowseResultsRenderer.tabs[0].tabRenderer.content.sectionListRenderer.contents[0].itemSectionRenderer.contents[0].playlistVideoListRenderer.contents[]`

Once the final "contents" elements are available, each video data can be retrieved via `playlistPanelVideoRenderer`:
- id: `videoId`
- title: `title.simpleText`
- duration: `lengthSeconds`

I think 2. is the best approach for a `getPlaylist(String id)` method that returns a basic video list and let the user choose.
Let me know if it's OK, I'll try to get back with a PR.
