### ISSUE TITLE
Is there Mp3 download support 

### ISSUE THREAD

**Issue by Shabinder** [sealedtx/java-youtube-downloader#37]
Its possible to download audio formats , like m4a , but i am just wondering is there a way to download audio in mp3 file format ? 
If not , is there any plan to implement that?

**Comment by xibr** [comment]
youtube does not have mp3 formats for audio, you need ffmpeg to convert audio to mp3. see [#5](https://github.com/sealedtx/java-youtube-downloader/issues/5)

**Comment by Shabinder** [comment]
Yeah doing that , just wanted to be know if downlowding as mp3 was possible , which u told isnt. Thanks
