### ISSUE TITLE
CipherException: Could not parse js function

### ISSUE THREAD

**Issue by ronanPoinsignon** [sealedtx/java-youtube-downloader#38]
Hello
I am using your api for +-2 weeks. This is really helpful, thank you a lot.
But i found some ytb id which generate this error : 

_com.github.kiulian.downloader.YoutubeException$CipherException: Could not parse js function
	at com.github.kiulian.downloader.cipher.CachedCipherFactory.parseFunction(CachedCipherFactory.java:188)
	at com.github.kiulian.downloader.cipher.CachedCipherFactory.getTransformFunctions(CachedCipherFactory.java:118)
	at com.github.kiulian.downloader.cipher.CachedCipherFactory.createCipher(CachedCipherFactory.java:90)
	at com.github.kiulian.downloader.parser.DefaultParser.parseFormat(DefaultParser.java:170)
	at com.github.kiulian.downloader.parser.DefaultParser.parseFormats(DefaultParser.java:126)
	at com.github.kiulian.downloader.YoutubeDownloader.getVideo(YoutubeDownloader.java:69)_

Some links which do not work : 
https://www.youtube.com/watch?v=Qe500eIK1oA
https://www.youtube.com/watch?v=RGwaDQURybk
https://www.youtube.com/watch?v=FvHHlKp923A

Maybe am i doing something wrong ? (i have release 2.2.2) 

Thx for your help.

**Comment by kangsLee** [comment]
[kangsLee/java-youtube-downloader](https://github.com/kangsLee/java-youtube-downloader)

I found this problem and fixed it.
please check out my brunch.

**Comment by manikshakya** [comment]
@kangsLee I can see the changes you made in the github for this issue and my maven build is synced as well but I am still getting YoutubeException$CipherException: Could not parse js function error.

Is there something I am missing..

**Comment by kangsLee** [comment]
Can you check if there is `(?:\\b|[^a-zA-Z0-9$])` in `CachedCipherFactory.class:INITIAL_FUNCTION_PATTERNS`?

**Comment by manikshakya** [comment]
@kangsLee it doesn't contain the regex you mention.. 
Also, when you fix the bug.. how can i download the updated version with maven??

**Comment by kangsLee** [comment]
@manikshakya 
I didn't upload my source to Jitpack. You can't use Maven now.
Please wait for 'pull requests' to be updated on this brunch.

**Comment by manikshakya** [comment]
@kangsLee I can see in the website that it has not been updated. How long does it take to update?
Also, How come I can't use the older version of the library? If 2.2.1 was working fine before why is it having the same problem as 2.2.2?

Thanks for the information and help.. kangsLee

**Comment by kangsLee** [comment]
This is an additional issue not occurring in 2.2.2.
I'm not a manager, so you have to wait for distribution.
If you have to use it urgently, use my brunch without maven.
HTH!

**Comment by xibr** [comment]
fixed by @kangsLee [#39](https://github.com/sealedtx/java-youtube-downloader/pull/39), now working.
@manikshakya waiting for @sealedtx‏ to merging this change.

**Comment by sealedtx** [comment]
@ronanPoinsignon Sorry for delay, already merged #39, will draft a new release soon. @xibr @kangsLee @manikshakya thank you all guys for being interested and keeping this project working

**Comment by xibr** [comment]
We thank you for your effort to keep this repo working and updated.
