### ISSUE TITLE
FileNotFound issue

### ISSUE THREAD

**Issue by barbetb** [sealedtx/java-youtube-downloader#43]
Hi guys,

Great library, but it looks like youtube is kinda trying to block you from downloading the urls. I implemented your library as said in the README. The library find the urls, but then downloading is impossible. Any idea what's causing this?

`java.io.FileNotFoundException: https://r5---sn-5hnednlk.googlevideo.com/videoplayback?expire=1596592358&ei=hrwpX8X6F4mQ1wakjZjoCA&ip=87.214.227.252&id=o-ALCnNkQPbS3bLETiGP3fP3TUx33UzwdhivIvNJQ-VcdW&itag=136&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=yt_otf&requiressl=yes&mh=Ok&mm=31%2C26&mn=sn-5hnednlk%2Csn-4g5ednsz&ms=au%2Conr&mv=m&mvi=5&pl=17&initcwndbps=996250&vprv=1&mime=video%2Fmp4&otf=1&otfp=1&dur=0.000&lmt=1596550688211966&mt=1596570577&fvip=5&keepalive=yes&fexp=23883098&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cotf%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANCCSQFVdqRQNO-UbvO1Mek8LVPIzubuMIkcBbnr2KtrAiA_6qNJ5KdfX_dnR6X6eQBv5gm6faPxfBIzrluaFq8Odw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIBnGSMkppK9b-AE2wxilE0Bm4r_CV2nhugXVcvtWjY0AiBJIH4PP2vhCUcOJVf8HMzfaNgIyhLSExFml9hVTs3hKg%3D%3D
`
[Downloader.txt](https://github.com/sealedtx/java-youtube-downloader/files/5024221/Downloader.txt)

**Comment by sealedtx** [comment]
@barbetb Hi! I have tried to investigate this problem. As I undestand youtube may provide urls with type "FORMAT_STREAM_TYPE_OTF" which lead to 404 NotFound. I don't know what is this format and why does youtube provide it. You may also see that "&dur=0.000" video duration is zero in your url, but should be non-zero.
As a solution I may filter those results and don't allow to download them.

**Comment by xibr** [comment]
Try with itag 22 or 18.

**Comment by barbetb** [comment]
Different format worked! Thanks a lot. I like the library, thanks for building and sharing.

**Comment by sealedtx** [comment]
https://github.com/sealedtx/java-youtube-downloader/commit/cca2129661065a05808cb459fd7909d164c6acea should cover this issue

**Comment by barbetb** [comment]
Thanks!
