### ISSUE TITLE
Is it possible to download audio in mp3 format?

### ISSUE THREAD

**Issue by trip2gafa** [sealedtx/java-youtube-downloader#5]

**Comment by bunaif** [comment]
yes, use ffmpeg Library to download  as mp3, check [README.md](https://github.com/yausername/youtubedl-android/blob/master/README.md) file To learn how to call ffmpeg library

**Comment by sealedtx** [comment]
@trip2gafa this repo does not provide any convertation methods, it parses urls from youtube, and unfortunately, youtube does not have mp3 formats for audio
