### ISSUE TITLE
Error to load url

### ISSUE THREAD

**Issue by SdidevelopWork** [sealedtx/java-youtube-downloader#50]
com.github.kiulian.downloader.YoutubeException$VideoUnavailableException: Could not load url:

**Comment by sealedtx** [comment]
@SdidevelopWork provide details

**Comment by SdidevelopWork** [comment]
Connection reset

**Comment by sealedtx** [comment]
@SdidevelopWork Example is present in README. Provide videoId which causes error.

**Comment by SdidevelopWork** [comment]
zWSFGIEAz4s

**Comment by sealedtx** [comment]
@SdidevelopWork I can successfully retrieve metadata for your videoId. The problem is with your connection to youtube. Did you use latest version of **java-youtube-downloader**? Error message seems to be from previous version. Please update to get more detailed error messages.

**Comment by SdidevelopWork** [comment]
Yes you are right
When I use a proxy in http connection can get information.
Can you provide a proxy input ?

**Comment by SdidevelopWork** [comment]
Yes you are right
When I use a proxy in http connection can get information.
Can you provide a proxy input ?

**Comment by sealedtx** [comment]
@SdidevelopWork what do you mean?
You can set proxy without changes in this library:
```
// set this before any action with YoutubeDownloader
Properties systemProperties = System.getProperties();
systemProperties.setProperty("http.proxyHost",proxy);
systemProperties.setProperty("http.proxyPort",port);
```

**Comment by SdidevelopWork** [comment]
I tried this way before, but it does not work

**Comment by sealedtx** [comment]
@SdidevelopWork It should be "http**s**.proxyHost" and "http**s**.proxyHost, sorry

**Comment by SdidevelopWork** [comment]
hello
My problem was solved.
What should I do to stop the download?

**Comment by sealedtx** [comment]
@SdidevelopWork do you want to interrupt downloading

**Comment by SdidevelopWork** [comment]
yes.

**Comment by sealedtx** [comment]
@SdidevelopWork There is no such functionality now, but I may implement it. Please, open new issue for this feature request

**Comment by SdidevelopWork** [comment]
Ok, thanks
