### ISSUE TITLE
Interrupt download

### ISSUE THREAD

**Issue by SdidevelopWork** [sealedtx/java-youtube-downloader#52]
no function available for stop download.
thank you.

**Comment by sealedtx** [comment]
@SdidevelopWork Currently I am able to add cancelation functionality only for `downloadAsync` which returns `Future<File>`, without breaking backward compatibility. Is it works for you?
The `downloadAsync` which uses callback listener can not be canceled for now. I will implement it in future releases which will bump major version to 3.x.x with more breaking changes.

**Comment by SdidevelopWork** [comment]
Yes.
Thank you.

**Comment by sealedtx** [comment]
@SdidevelopWork Actually I have managed to add cancellation functionality to both downloadAsync (with and without callback) without breaking backward compatibility:
```
// async downloading with callback
Future<File> future = video.downloadAsync(videoFormats.get(0), outputDir, new OnYoutubeDownloadListener() {
    @Override
    public void onDownloading(int progress) {
    }
            
    @Override
    public void onFinished(File file) {
    }

    @Override
    public void onError(Throwable throwable) {
        // throwable is instance of CancellationException
        System.out.println("Error: " + throwable.getMessage());
    }
});

// async downloading without callback
Future<File> future = video.downloadAsync(format, outputDir);

// cancel downloading
future.cancel(true); // true is required to interrupt downloading thread

future.get() // throws CancellationException
```
Check out new release 2.4.0 if you need this functionality. Thank you.

**Comment by SdidevelopWork** [comment]
Thank you.
