### ISSUE TITLE
com.github.kiulian.downloader.YoutubeException$BadPageException: Could not parse web page

### ISSUE THREAD

**Issue by silleruss** [sealedtx/java-youtube-downloader#54]
I can't parsing this from URL -> https://www.youtube.com/watch?v=OtIMeAt2lTY
And i found the 'ytplayer.config' was empty, how can i parse that URL and get a video data?

It was fine when i tested it locally, but can't parsing when i tested it my product server

**Comment by xibr** [comment]
If you open the link in the browser, you will see a message saying the content is not available.

**Comment by silleruss** [comment]
but it was working at local server, should i something wrong from product server?

**Comment by xibr** [comment]
I have no idea wait @sealedtx's he'll answer you.

**Comment by sealedtx** [comment]
@xibr Thank you! Yes, you are right, if video is not available in browser it is also not available via **java-youtube-downloader**, because it parses webpage
@silleruss May be video was available at the time you test is at local server, but later became not available

**Comment by silleruss** [comment]
Thank you for your advice @xibr and @sealedtx  i understand it
