### ISSUE TITLE
Question on extensions

### ISSUE THREAD

**Issue by dspolimi** [sealedtx/java-youtube-downloader#57]
I noticed that if there are multiple _AudioFormats_ for audio download, not all formats get to a _.m4a_ file, but some get to a _.weba_ file.
Is there a way to avoid that?

**Comment by sealedtx** [comment]
@dspolimi Avoid what? For `AudioFormat` if mime type contains **webm** - the extention will be **.weba**, if mime type contains **mp4** - the extenstion will be **m4a**
https://github.com/sealedtx/java-youtube-downloader/blob/6b2f21d3dd3ed92a7de2a68e5512ea674a51587a/src/main/java/com/github/kiulian/downloader/model/formats/Format.java#L65-L83

**Comment by dspolimi** [comment]
> @dspolimi Avoid what? For `AudioFormat` if mime type contains **webm** - the extention will be **.weba**, if mime type contains **mp4** - the extenstion will be **m4a**
> https://github.com/sealedtx/java-youtube-downloader/blob/6b2f21d3dd3ed92a7de2a68e5512ea674a51587a/src/main/java/com/github/kiulian/downloader/model/formats/Format.java#L65-L83

Thank you for the quick answer.
Is there a way to always download m4a files, or do i have to convert the file?

**Comment by sealedtx** [comment]
@dspolimi This library does not convert any format itself, it just parses metadata and provide url to formats provided by Youtube. If format is provided with ** webm** format - the file you are going to download is encoded with webm codecs by Youtube and thats how it works. Just select format with extension which suits you.
