### ISSUE TITLE
Every videoId I try is unavailable ;/

### ISSUE THREAD

**Issue by matthias-schneglberger** [sealedtx/java-youtube-downloader#6]
For the Video-ID:
https://www.youtube.com/watch?v=5pXVLqupV3o

I get the Exception:
Exception in thread "main" com.github.kiulian.downloader.YoutubeException$VideoUnavailableException: Video unavailable
	at com.github.kiulian.downloader.YoutubeDownloader.getVideo(YoutubeDownloader.java:76)

What is wrong with the ID?
I hope you can help me!

**Comment by sealedtx** [comment]
@matthias-schneglberger, Hi, sorry for delay. I had no spare time to support this repo. But this weekend I am going to write fixes to bring it back to life. Moreover I have plant to add support for downloading ciphered videos with signature.

**Comment by matthias-schneglberger** [comment]
Thank you now it works!

But I've got one more question -> Am I able to download mp3 files?

**Comment by bunaif** [comment]
@matthias-schneglberger  YouTube does not support mp3 files, [#5](https://github.com/sealedtx/java-youtube-downloader/issues/5)

**Comment by matthias-schneglberger** [comment]
Ok thank you

**Comment by ErasedRhythm** [comment]
Having the same problem. Did some testing and found the problem in the `DefaultExtractor::loadUrl()`. `connection.getInputStream()` is throwing the error `java.io.IOException: Server returned HTTP response code: 429 for URL: https://www.youtube.com/watch?v=123abc`

I am not requesting massive amounts of videos. My code worked with the exact same videos already, but now it gives me these errors when I requested the first video today.

**Comment by sealedtx** [comment]
@ErasedRhythm Hi, basically 429 means "rate limiting", you could try change your IP address or simply User-Agent with `downloader.setParserRequestProperty("User-Agent", "...")`. If it does not help and you are sure that the problem is in my code - be welcome to open new issue with more details
