### ISSUE TITLE
Error parsing Format

### ISSUE THREAD

**Issue by BelaJonasB** [sealedtx/java-youtube-downloader#61]
**Hey, I have a backend where I dowload vidoes with a given link in a header to my server.
It all worked fine for some time, but suddenly without changing somthing I get a "Error parsing Format Error" for some seemingly random itags when i try to download something.**

**This is the Error:**
      `Error parsing format: {"itag":18,"fps":24,"projectionType":"RECTANGULAR","bitrate":597165,"mimeType":"video/mp4;             codecs=\"avc1.42001E, mp4a.40.2\"","audioQuality":"AUDIO_QUALITY_LOW","approxDurationMs":"323477","audioSampleRate":"44100","quality":"medium","qualityLabel":"360p","audioChannels":2,"signatureCipher":"s=%3D%3DQHYHiQ24nQrGJ1gQ3zI9t071irzyZcth2RWCLd33xc-DQIC4K3lTASTOJRevPnQd1jR741W_-VaJuce3UPqN-j5HiPgIQRw8JQ0qOAORAOR&sp=sig&url=https://r7---sn-uxax4vopj5qx-q0ne.googlevideo.com/videoplayback%3Fexpire%3D1603834560%26ei%3DYD6YX5OgE5CD6dsPh6iwuAQ%26ip%3D2.243.9.172%26id%3Do-AHS5Ws24ubIMTgz8oHqwTXUVKrYowkikLc6whmJB4XcI%26itag%3D18%26source%3Dyoutube%26requiressl%3Dyes%26mh%3Dlq%26mm%3D31%252C29%26mn%3Dsn-uxax4vopj5qx-q0ne%252Csn-4g5e6nsr%26ms%3Dau%252Crdu%26mv%3Dm%26mvi%3D7%26pcm2cms%3Dyes%26pl%3D18%26gcr%3Dde%26initcwndbps%3D633750%26vprv%3D1%26mime%3Dvideo%252Fmp4%26gir%3Dyes%26clen%3D24140877%26ratebypass%3Dyes%26dur%3D323.477%26lmt%3D1584416382731509%26mt%3D1603812763%26fvip%3D3%26c%3DWEB%26txp%3D5531432%26sparams%3Dexpire%252Cei%252Cip%252Cid%252Citag%252Csource%252Crequiressl%252Cgcr%252Cvprv%252Cmime%252Cgir%252Cclen%252Cratebypass%252Cdur%252Clmt%26lsparams%3Dmh%252Cmm%252Cmn%252Cms%252Cmv%252Cmvi%252Cpcm2cms%252Cpl%252Cinitcwndbps%26lsig%3DAG3C_xAwRgIhAPAuWaSiAbsdvxcGT-V5y8YoQw807hPQaM2Cp4Th2_HuAiEA5xjiRYuzD-UK3V7FxzmN2AfKN5qX9fjekZoNJspR1f8%253D","width":640,"contentLength":"24140877","lastModified":"1584416382731509","height":360,"averageBitrate":597034}
`

**Which repeats for a couple of itags (which I am not trying to use/format) and at the end of the log it says:**

`java.lang.NullPointerException
	at com.github.kiulian.downloader.model.Utils.getOutputFile(Utils.java:50)
	at com.github.kiulian.downloader.model.YoutubeVideo.initDownload(YoutubeVideo.java:210)
	at com.github.kiulian.downloader.model.YoutubeVideo.download(YoutubeVideo.java:173)
	at com.github.kiulian.downloader.model.YoutubeVideo.download(YoutubeVideo.java:169)
	at Main.Rome.lambda$posts$4(Rome.java:128)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1584)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:501)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**This is my code:
There are some useless parts at the moment, like the connection to the YouTube API and the error occurs when trying to use the /insert method.**

```
`package Main;

import com.github.kiulian.downloader.YoutubeDownloader;
import com.github.kiulian.downloader.model.VideoDetails;
import com.github.kiulian.downloader.model.YoutubeVideo;
import com.github.kiulian.downloader.model.formats.Format;
import com.google.api.client.googleapis.javanet.GoogleNetHttpTransport;
import com.google.api.client.http.javanet.NetHttpTransport;
import com.google.api.client.json.JsonFactory;
import com.google.api.client.json.jackson2.JacksonFactory;
import com.google.api.services.youtube.YouTube;
import com.google.api.services.youtube.model.VideoListResponse;
import com.google.gson.Gson;
import parser.Row;

import java.io.File;
import java.io.IOException;
import java.security.GeneralSecurityException;
import java.sql.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static spark.Spark.*;

public class Rome {
    static YoutubeDownloader downloader = new YoutubeDownloader();
    static Gson g = new Gson();
    static Connection connection = null;
    private static final String DEVELOPER_KEY = *censored*;
    private static final String APPLICATION_NAME = "Video";
    private static final JsonFactory JSON_FACTORY = JacksonFactory.getDefaultInstance();

    //Formatting (JSON) and Http Client
    public static YouTube getService() throws GeneralSecurityException, IOException {
        final NetHttpTransport httpTransport = GoogleNetHttpTransport.newTrustedTransport();
        return new YouTube.Builder(httpTransport, JSON_FACTORY, null)
                .setApplicationName(APPLICATION_NAME)
                .build();
    }

    public static void main(String[] args) {
        port(80);
        connect();
        options("/*",
                (request, response) -> {

                    String accessControlRequestHeaders = request
                            .headers("Access-Control-Request-Headers");
                    if (accessControlRequestHeaders != null) {
                        response.header("Access-Control-Allow-Headers",
                                accessControlRequestHeaders);
                    }

                    String accessControlRequestMethod = request
                            .headers("Access-Control-Request-Method");
                    if (accessControlRequestMethod != null) {
                        response.header("Access-Control-Allow-Methods",
                                accessControlRequestMethod);
                    }

                    return "OK";
                });
        before((request, response) -> response.header("Access-Control-Allow-Origin", "*"));

        posts();
        gets();
        deletes();


    }


    public static void gets() {
        get("/random/:current", (req,resp) -> {


            //Random row
            List<Row> rows = rowsToList();
            Collections.shuffle(rows);

            int i=0;
            if(rows.get(0).getId()==Integer.parseInt(req.params("current"))) {
                i=1;
            }

            resp.status(200);
            resp.type("application/json");
            return g.toJson(rows.get(i));
        });

        get("/all", (req,resp) -> {
            List<Row> rows = rowsToList();

            resp.status(200);
            resp.type("application/json");
            return g.toJson(rows);
        });
    }

    private static List<Row> rowsToList() throws SQLException {
        PreparedStatement pre = connection.prepareStatement("SELECT * FROM urls");
        ResultSet res = pre.executeQuery();
        List<Row> rows = new ArrayList<>();
        res.next();
        while(res.next()) {
            Row r = new Row(res.getInt(2),res.getString(1),res.getString(3),res.getString(4));
            rows.add(r);
        }
        return rows;
    }

    public static void posts() {
        post("/insert", (req,resp)-> {

            //get Video ID
            String id = req.headers("link").replaceFirst("https://www.youtube.com/watch\\?v=","");

            File file = null;
            String title = null;
            //download vid and put to files
            try {
                YoutubeVideo video = downloader.getVideo(id);
                VideoDetails details = video.details();
                title = video.details().title();
                Format formatByItag = video.findFormatByItag(251);
                File outputDir = new File("/opt/storage/public");
                file = video.download(formatByItag, outputDir, video.details().title().replaceAll("[^a-zA-Z0-9]+", "_"));
            } catch (Exception e) {
                e.printStackTrace();
            }

            //DB entry
            PreparedStatement pre = connection.prepareStatement("INSERT INTO urls (link,title,videoid) VALUES (?,?,?)");
            assert file != null;
            pre.setString(1,file.getName());
            pre.setString(2,title);
            pre.setString(3,id);
            pre.executeUpdate();

            resp.status(200);
            resp.type("text");
            return "done";
        });
    }

    public static void deletes() {
        delete("/:id",(req,resp) -> {
            PreparedStatement pre = connection.prepareStatement("DELETE FROM urls WHERE id=?");
            pre.setInt(1, Integer.parseInt(req.params(":id")));
            pre.executeUpdate();
            
            resp.status(200);
            resp.type("application/json");
            return "done";
        });
    }


    //Connect to DB
    public static void connect() {
        try {
            connection = DriverManager.getConnection("jdbc:postgresql://192.168.178.56:5432/sync?user=*censored*");
        }catch (Exception e) {
            e.printStackTrace();
        }
    }
}
`
```

**Comment by sealedtx** [comment]
@BelaJonasB Hi. There are 2 different problems. Error while parsing formats could be same as here #59, probably is already fixed in last commit and will be included in next release. Currently available here:
```
<dependency>
	    <groupId>com.github.sealedtx</groupId>
	    <artifactId>java-youtube-downloader</artifactId>
	    <version>86bef0f47e</version>
</dependency>
```
Second problem is NullPointerException in getOutputFile, the problem: not all videos have same formats, `findFormatByItag` may return `null` if there is no such format.
Replace this:
`Format formatByItag = video.findFormatByItag(251)`, 
with:
`List<Format> formats = video.formats()`
and take the one which suits your needs.

**Comment by BelaJonasB** [comment]
@sealedtx Thanks for the quick reply.

`List<Format> formats = video.formats()`
returns an empty list for me. I used it like this:
```
YoutubeVideo video = downloader.getVideo(id);
List<Format> formats = video.formats();
System.out.println("array: "+Arrays.toString(formats.toArray()));
System.out.println("selected: "+formats.get(0));
```
And do you happen to have the Gradle dependency for the version that you mentioned?

**Comment by sealedtx** [comment]
@BelaJonasB gradle is the same: `implementation 'com.github.sealedtx:java-youtube-downloader:86bef0f47e'`. Try it, if still no formats, provide videoId, so I can check.

**Comment by 8o8aua** [comment]
@sealedtx Could you please tell me when are you going to release this fix?

**Comment by sealedtx** [comment]
@8o8aua issue with js url extraction is fixed and released in patch 2.4.2

**Comment by 8o8aua** [comment]
@sealedtx Thank you very much for your library

**Comment by BelaJonasB** [comment]
@sealedtx 
The update fixed it, thank you!
