### ISSUE TITLE
Deciphering not working anymore

### ISSUE THREAD

**Issue by MCrissDev** [sealedtx/java-youtube-downloader#72]
Hello,

Seems to receive: com.github.kiulian.downloader.YoutubeException$CipherException: Could not parse js function

Example video:
https://www.youtube.com/watch?v=82gcaIFUtiI

**Comment by Fabulierer** [comment]
Was able to reproduce this, but seems like only this video is affected by it. At least I haven't seen this error before, and I have downloaded a lot of videos (mostly music) with this library.

**Comment by MCrissDev** [comment]
There are many other videos that i can give as an example.

**Comment by Fabulierer** [comment]
Is there any pattern to them that you've noticed?

**Comment by kangsLee** [comment]
@Fabulierer 
A new pattern ["do"] function has been identified.

**Comment by Shabinder** [comment]
> Seems to receive: com.github.kiulian.downloader.YoutubeException$CipherException: **Could not parse js function**


**+1** i have been experiencing the same issue on some videos

**Comment by sealedtx** [comment]
Hi, I will try to investigate the problem. Also appreciate any kind of help

**Comment by sealedtx** [comment]
Links for video with signature which still works (if such exists) may help.

**Comment by seefa** [comment]
@kangsLee is right. I added one more pattern to support both, ```A.do()``` and ```A["do"]()``` and this exception passed. But it seems Youtube changed its signature pattern. So another exception about Cipher pattern will raise. Code is written pretty clean. 
I hope @sealedtx or others find dynamic algorithm for this part of code.

**Comment by sealedtx** [comment]
I found the solution. Please wait next commit

**Comment by sealedtx** [comment]
New release 2.5.1 is ready

**Comment by MCrissDev** [comment]
Thank you. I can confirm that the new version is working. Closing.

**Comment by seefa** [comment]
@sealedtx Thank you so much, You're right everything fixed.
