### ISSUE TITLE
Does not extract audio correctly

### ISSUE THREAD

**Issue by MCrissDev** [sealedtx/java-youtube-downloader#76]
Hello,
Found a link that the library is unable to extract the audio link correctly:

https://www.youtube.com/watch?v=9GlKcBbYpVk

**Comment by sealedtx** [comment]
@MCrissDev Hi, you videoId `9GlKcBbYpVk` works fine for me. Please, provide detailed error message/stacktrace, etc.

**Comment by MCrissDev** [comment]
Hello,
An audio link is extracted but that link is invalid (can't be used by browser for example)

**Comment by sealedtx** [comment]
@MCrissDev provide your code snippet and fresh extracted links

**Comment by MCrissDev** [comment]
Hello,

Extracted link: https://r1---sn-gqn-ujxl.googlevideo.com/videoplayback?expire=1617730749&ei=XUhsYNLTBMaMgAfB47ugBw&ip=5.13.137.233&id=o-AC3Agx7M9KvFjL1mreyjOKbjo6CxPKfttnky6HyD4Xup&itag=140&source=youtube&requiressl=yes&mh=wD&mm=31%2C29&mn=sn-gqn-ujxl%2Csn-c0q7lnsl&ms=au%2Crdu&mv=m&mvi=1&pl=19&initcwndbps=1351250&vprv=1&mime=audio%2Fmp4&ns=NkBiTVL5xKbZdPwYshZIVpoF&gir=yes&clen=2934160&dur=181.231&lmt=1615637300749969&mt=1617708538&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5531432&n=Dr3H9WkWWIVaIdo1&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgeTmQ0wz1-J0ZOYBUlIy9N7ZZTC7f5mIC8W5FO0NKUWsCIDf2LBPmeiSQ3hpwT9Mj7sbZlca3iHmpFW9VxvjfyTpX&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAJEopb4QAzHG7ltO4KkbAEYlydeLggZrC6bZNB3zF-ZLAiBHDzBQH_8eXuxEzGve6c6h24Ll-FbslwEJG80R1O7zUg%3D%3D

Some code snippet:

 YoutubeDownloader downloader = new YoutubeDownloader();
                    downloader.setParserRetryOnFailure(2);
                    YoutubeVideo video = downloader.getVideo(media.getMediaId());
                    if (video == null) {
                        sCount++;
                        getAudioDownloadLink(context, media, listener);
                        return;
                    }
                    List<AudioFormat> audioFormats = video.audioFormats();
                    Log.e(TAG, "~~~~~~~~~ audioFormat = " + audioFormats.size());

                    if (audioFormats.size() > 0) {
                        AudioFormat finalFormat = null;
                        for (AudioFormat format : audioFormats) {
                            Log.e(TAG, "~~~~ probing format = " + format.itag().id() + " uri = "+format.url());
                            if (checkYtbURL(format.url())) {
                                finalFormat = format;
                                break;
                            }
                        }

**Comment by sealedtx** [comment]
@MCrissDev your extracted link works for me, audio is playing in my browser Google Chrome. 
I believe the problem is with your browser or network. What is the response for your link? Is it HTTP 200 or 404 or 403? 
Try download your format and check the file:
```java
File outputDir = new File("my_audios");
// sync downloading
File file = video.download(finalFormat, outputDir);
```

**Comment by MCrissDev** [comment]
That's very strange. Yesterday that link did not work at all but others did. Today, that link works as well.
Closing this issue, thank you very much for the support.
