### ISSUE TITLE
Expose methods that download youtube audio/video data in-memory

### ISSUE THREAD

**Issue by jamesvickers19** [sealedtx/java-youtube-downloader#77]
I was wondering if some private methods of `YoutubeDownloader` could be made public to allow processing of the data in-memory?  In particular [downloadStraight](https://github.com/sealedtx/java-youtube-downloader/blob/cc7ae9c675d5f27753eb4392779ac5717c5eedb0/src/main/java/com/github/kiulian/downloader/model/YoutubeVideo.java#L223) which would allow one to provide an `OutputStream`?  Or perhaps some way that includes the switching between `downloadStraight` and `downloadByPart` appropriately but doesn't write it to a `File`.

Happy to work on a pull request, just checking if the project would be against this and looking for some design input.

Thanks!

**Comment by sealedtx** [comment]
@jamesvickers19 sure, pull requests are welcomed. You may add overloaded `download` methods to works to `OutputStream` instead of `File`. Will this work for your needs?

**Comment by jamesvickers19** [comment]
Added a PR :)

https://github.com/sealedtx/java-youtube-downloader/pull/78
