### ISSUE TITLE
Is there function support video convert to mp3 format?

### ISSUE THREAD

**Issue by hk200** [sealedtx/java-youtube-downloader#87]
In some scenario, there is need to convert video to mp3 format.
Is there function support video convert to mp3 format?

**Comment by xibr** [comment]
you need ffmpeg to convert audio to mp3.  [#5](https://github.com/sealedtx/java-youtube-downloader/issues/5)

**Comment by sealedtx** [comment]
@hk200 this library does not support any converting, it only parse data provided by youtube. To convert you may use other libraries such as ffmpeg

**Comment by hk200** [comment]
> @hk200 this library does not support any converting, it only parses data provided by youtube. To convert you may use other libraries such as ffmpeg

many thanks
