### ISSUE TITLE
there is many duplicated resolutions  and size of video, which one is correct one.

### ISSUE THREAD

**Issue by hk200** [sealedtx/java-youtube-downloader#88]
Hi
 i make a test page of video download and get a lot of duplicated resolution. Which one is the correct one of the same resolution?
the remote url is: https://www.youtube.com/watch?v=vDQwzkxwHTs
![issue20210629001](https://user-images.githubusercontent.com/15417222/123756526-98f66500-d8ef-11eb-87d0-e42af5492173.png)

**Comment by sealedtx** [comment]
@hk200 I assume that those duplicates may be different extensions: mp4, wemb etc. Check it out

**Comment by hk200** [comment]
I filtered duplicated format and found there is only 2 of format videos with audio(1 of 360p and 1 of 720p), many format without audio. Is the youtube play video steam without sound and audio steam at the same time at higher format like 1080p, 4k, etc?

**Comment by sealedtx** [comment]
@hk200 I am not aware of this, but I may assume that they are combining video and audio for higher quality formats. Formats `VideoWithAudioFormat` usually have not the best quality, you may retrieve them with:
```java
// get videos formats only with audio
List<VideoWithAudioFormat> videoWithAudioFormats = videoInfo.videoWithAudioFormats();
```

**Comment by hk200** [comment]
> @hk200 I am not aware of this, but I may assume that they are combining video and audio for higher quality formats. Formats `VideoWithAudioFormat` usually have not the best quality, you may retrieve them with:
> 
> ```java
> // get videos formats only with audio
> List<VideoWithAudioFormat> videoWithAudioFormats = videoInfo.videoWithAudioFormats();
> ```

Though their all higher resolution without audio, their online higher resolution videos do have audio output. I assume their online player make a some combination presentation of the video stream and audio steam based on there is no higher steam with audio available.
Do you have some hints to prove my assumption？

**Comment by sealedtx** [comment]
@hk200 I don't have any proves, but it may be the only way to do so

**Comment by hk200** [comment]
> @hk200 I don't have any proves, but it may be the only way to do so

I agree with you.

**Comment by hk200** [comment]
> @hk200 I don't have any proves, but it may be the only way to do so

I agree with you.

**Comment by hk200** [comment]
Is there any merge tool available of video and audio stream by java?

**Comment by sealedtx** [comment]
@hk200 the only tool I have worked with - ffmpeg

**Comment by xibr** [comment]
@hk200 maybe something like https://github.com/sannies/mp4parser

Take a look at https://github.com/HaarigerHarald/android-youtubeExtractor/blob/master/advancedDownloader/src/main/java/at/huber/youtubeDownloader/DownloadFinishedReceiver.java

**Comment by hk200** [comment]
> @hk200 the only tool I have worked with - ffmpeg




> @hk200 maybe something like https://github.com/sannies/mp4parser
> 
> Take a look at https://github.com/HaarigerHarald/android-youtubeExtractor/blob/master/advancedDownloader/src/main/java/at/huber/youtubeDownloader/DownloadFinishedReceiver.java

thanks, I ll check that out.
seems ffmpeg accpets url input.
