### ISSUE TITLE
cant get the 720p video size by remote url

### ISSUE THREAD

**Issue by hk200** [sealedtx/java-youtube-downloader#89]
Hi
  I make a video testing by url: https://www.youtube.com/watch?v=vDQwzkxwHTs and cannot get the 720p format video size. 
The information of the video format size is null.

**Comment by sealedtx** [comment]
@hk200 please, provide code snippet

**Comment by hk200** [comment]
> @hk200 please, provide code snippet

[VideoController.java.txt](https://github.com/sealedtx/java-youtube-downloader/files/6737869/VideoController.java.txt)
[VideoInfoVo.java.txt](https://github.com/sealedtx/java-youtube-downloader/files/6737870/VideoInfoVo.java.txt)

**Comment by sealedtx** [comment]
@hk200 code snippet means small part of your code that I can run to reproduce your problem (without external libraries). 
I just checked your videoId `vDQwzkxwHTs` and I recieved these 720p formats:
**contaier, itag, qualityLabel**
mp4, 22, 720p
mp4, 136, 720p
webm, 247, 720p
mp4, 398, 720p

**Comment by hk200** [comment]
ok, there is 4 format video info match the itag
720p unkown(about 80M actually) size: video ok,  should be i22(VideoQuality.hd720, AudioQuality.medium),
720p 72.0MB size: video without sound ,  mp4 i136(VideoQuality.hd720),
720p 62.0MB size:video without sound , webm i247(VideoQuality.hd720),
720p 48.0MB size:video cannot open , av01 video only formats  i398(VideoQuality.hd720),

the video taged i22 720p cannot get the contentLength for null for testing.

**Comment by xibr** [comment]
YouTube does not provide file size, If you take a look at youtube-dl you will notice that the file size is not available for itag 22 
`"filesize":null`

**Comment by xibr** [comment]
About formats run `youtube-dl -F https://www.youtube.com/watch?v=vDQwzkxwHTs`

You can find out why there are many 720p

```
[youtube] vDQwzkxwHTs: Downloading webpage
[info] Available formats for vDQwzkxwHTs:
format code  extension  resolution note
249          webm       audio only tiny   54k , webm_dash container, opus @ 54k (48000Hz), 1.85MiB
250          webm       audio only tiny   71k , webm_dash container, opus @ 71k (48000Hz), 2.44MiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 4.40MiB
251          webm       audio only tiny  140k , webm_dash container, opus @140k (48000Hz), 4.77MiB
394          mp4        256x144    144p   74k , mp4_dash container, av01.0.00M.08@  74k, 30fps, video only, 2.54MiB
278          webm       256x144    144p   85k , webm_dash container, vp9@  85k, 30fps, video only, 2.92MiB
160          mp4        256x144    144p  101k , mp4_dash container, avc1.4d400c@ 101k, 30fps, video only, 3.44MiB
395          mp4        426x240    240p  160k , mp4_dash container, av01.0.00M.08@ 160k, 30fps, video only, 5.45MiB
242          webm       426x240    240p  188k , webm_dash container, vp9@ 188k, 30fps, video only, 6.42MiB
133          mp4        426x240    240p  220k , mp4_dash container, avc1.4d4015@ 220k, 30fps, video only, 7.50MiB
396          mp4        640x360    360p  337k , mp4_dash container, av01.0.01M.08@ 337k, 30fps, video only, 11.49MiB
243          webm       640x360    360p  402k , webm_dash container, vp9@ 402k, 30fps, video only, 13.69MiB
134          mp4        640x360    360p  483k , mp4_dash container, avc1.4d401e@ 483k, 30fps, video only, 16.45MiB
397          mp4        854x480    480p  611k , mp4_dash container, av01.0.04M.08@ 611k, 30fps, video only, 20.78MiB
244          webm       854x480    480p  735k , webm_dash container, vp9@ 735k, 30fps, video only, 25.02MiB
135          mp4        854x480    480p  782k , mp4_dash container, avc1.4d401f@ 782k, 30fps, video only, 26.60MiB
398          mp4        1280x720   720p 1218k , mp4_dash container, av01.0.05M.08@1218k, 30fps, video only, 41.43MiB
136          mp4        1280x720   720p 1273k , mp4_dash container, avc1.4d401f@1273k, 30fps, video only, 43.31MiB
247          webm       1280x720   720p 1459k , webm_dash container, vp9@1459k, 30fps, video only, 49.64MiB
399          mp4        1920x1080  1080p 2174k , mp4_dash container, av01.0.08M.08@2174k, 30fps, video only, 73.92MiB
248          webm       1920x1080  1080p 2589k , webm_dash container, vp9@2589k, 30fps, video only, 88.05MiB
137          mp4        1920x1080  1080p 3781k , mp4_dash container, avc1.640028@3781k, 30fps, video only, 128.58MiB
400          mp4        2560x1440  1440p 6878k , mp4_dash container, av01.0.12M.08@6878k, 30fps, video only, 233.90MiB
271          webm       2560x1440  1440p 8249k , webm_dash container, vp9@8249k, 30fps, video only, 280.49MiB
401          mp4        3840x2160  2160p 13661k , mp4_dash container, av01.0.12M.08@13661k, 30fps, video only, 464.52MiB
313          webm       3840x2160  2160p 17344k , webm_dash container, vp9@17344k, 30fps, video only, 589.74MiB
18           mp4        640x360    360p  738k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 25.12MiB
22           mp4        1280x720   720p 1407k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
```

**Comment by hk200** [comment]
> About formats run `youtube-dl -F https://www.youtube.com/watch?v=vDQwzkxwHTs`
> 
> You can find out why there are many 720p
> 
> ```
> [youtube] vDQwzkxwHTs: Downloading webpage
> [info] Available formats for vDQwzkxwHTs:
> format code  extension  resolution note
> 249          webm       audio only tiny   54k , webm_dash container, opus @ 54k (48000Hz), 1.85MiB
> 250          webm       audio only tiny   71k , webm_dash container, opus @ 71k (48000Hz), 2.44MiB
> 140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 4.40MiB
> 251          webm       audio only tiny  140k , webm_dash container, opus @140k (48000Hz), 4.77MiB
> 394          mp4        256x144    144p   74k , mp4_dash container, av01.0.00M.08@  74k, 30fps, video only, 2.54MiB
> 278          webm       256x144    144p   85k , webm_dash container, vp9@  85k, 30fps, video only, 2.92MiB
> 160          mp4        256x144    144p  101k , mp4_dash container, avc1.4d400c@ 101k, 30fps, video only, 3.44MiB
> 395          mp4        426x240    240p  160k , mp4_dash container, av01.0.00M.08@ 160k, 30fps, video only, 5.45MiB
> 242          webm       426x240    240p  188k , webm_dash container, vp9@ 188k, 30fps, video only, 6.42MiB
> 133          mp4        426x240    240p  220k , mp4_dash container, avc1.4d4015@ 220k, 30fps, video only, 7.50MiB
> 396          mp4        640x360    360p  337k , mp4_dash container, av01.0.01M.08@ 337k, 30fps, video only, 11.49MiB
> 243          webm       640x360    360p  402k , webm_dash container, vp9@ 402k, 30fps, video only, 13.69MiB
> 134          mp4        640x360    360p  483k , mp4_dash container, avc1.4d401e@ 483k, 30fps, video only, 16.45MiB
> 397          mp4        854x480    480p  611k , mp4_dash container, av01.0.04M.08@ 611k, 30fps, video only, 20.78MiB
> 244          webm       854x480    480p  735k , webm_dash container, vp9@ 735k, 30fps, video only, 25.02MiB
> 135          mp4        854x480    480p  782k , mp4_dash container, avc1.4d401f@ 782k, 30fps, video only, 26.60MiB
> 398          mp4        1280x720   720p 1218k , mp4_dash container, av01.0.05M.08@1218k, 30fps, video only, 41.43MiB
> 136          mp4        1280x720   720p 1273k , mp4_dash container, avc1.4d401f@1273k, 30fps, video only, 43.31MiB
> 247          webm       1280x720   720p 1459k , webm_dash container, vp9@1459k, 30fps, video only, 49.64MiB
> 399          mp4        1920x1080  1080p 2174k , mp4_dash container, av01.0.08M.08@2174k, 30fps, video only, 73.92MiB
> 248          webm       1920x1080  1080p 2589k , webm_dash container, vp9@2589k, 30fps, video only, 88.05MiB
> 137          mp4        1920x1080  1080p 3781k , mp4_dash container, avc1.640028@3781k, 30fps, video only, 128.58MiB
> 400          mp4        2560x1440  1440p 6878k , mp4_dash container, av01.0.12M.08@6878k, 30fps, video only, 233.90MiB
> 271          webm       2560x1440  1440p 8249k , webm_dash container, vp9@8249k, 30fps, video only, 280.49MiB
> 401          mp4        3840x2160  2160p 13661k , mp4_dash container, av01.0.12M.08@13661k, 30fps, video only, 464.52MiB
> 313          webm       3840x2160  2160p 17344k , webm_dash container, vp9@17344k, 30fps, video only, 589.74MiB
> 18           mp4        640x360    360p  738k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 25.12MiB
> 22           mp4        1280x720   720p 1407k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
> ```

many thanks , the issue is caused by source.
