### ISSUE TITLE
test no sound of multi-format downloaded video

### ISSUE THREAD

**Issue by hk200** [sealedtx/java-youtube-downloader#90]
Hi
  I use the remote video url:https://www.youtube.com/watch?v=ZHDxWo-EdjU for testing and found there is no sound of multi-format downloaded video, 1 of 720p is ok, 2 of 720p without sound and 1 cannot open.
there is full test of 720p format
720p unkown(about 80M actually) size: video ok
720p 72.0MB size: video without sound
720p  62.0MB size:video without sound
720p 48.0MB size:video cannot open

**Comment by sealedtx** [comment]
@hk200 as i said in #88 those duplicates are just different containers and codecs, you may check its **itag** with `Format.itag()`. Have a look at https://github.com/sealedtx/java-youtube-downloader/blob/master/src/main/java/com/github/kiulian/downloader/model/videos/formats/Itag.java

**Comment by hk200** [comment]
> @hk200 as i said in #88 those duplicates are just different containers and codecs, you may check its **itag** with `Format.itag()`. Have a look at https://github.com/sealedtx/java-youtube-downloader/blob/master/src/main/java/com/github/kiulian/downloader/model/videos/formats/Itag.java

ok, thanks, i ll check it out.
