### ISSUE TITLE
Read error: ssl=0xebecf088: Failure in SSL library

### ISSUE THREAD

**Issue by aneebji** [sealedtx/java-youtube-downloader#94]
SSL issue while downloading video

Read error: ssl=0xebecf088: Failure in SSL library, usually a protocol error
    error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT (external/boringssl/src/crypto/fipsmodule/cipher/e_aes.c:1307 0xe6beba43:0x00000000)
    error:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC (external/boringssl/src/ssl/tls_record.cc:298 0xe6beba43:0x00000000)

**Comment by sealedtx** [comment]
@aneebji HI, I believe your problem is not caused by this library, because it uses only Java built in network api. Please look at stackoverflow similar issues https://stackoverflow.com/questions/29916962/javax-net-ssl-sslhandshakeexception-javax-net-ssl-sslprotocolexception-ssl-han
