### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SudoDios** [sealedtx/java-youtube-downloader#95]
{
"data":{
},
"error":{
"cause":{
"detailMessage":"streamingData and videoDetails not found",
"stackTrace":{
},
"suppressedExceptions":{
}
},
"detailMessage":"me.sudodios.youtubedownloader.extract.YoutubeException$BadPageException: streamingData and videoDetails not found",
"stackTrace":{
},
"suppressedExceptions":{
}
}
}

**Comment by sealedtx** [comment]
@SudoDios Please, add more details. When it happens? What videoId? Code snippet?

**Comment by SudoDios** [comment]
The problem was me.  
Solved.  
Sorry.
