### ISSUE TITLE
download video very slow

### ISSUE THREAD

**Issue by hk200** [sealedtx/java-youtube-downloader#97]
Hi
  when I did a test  using download api that use the test url "https://www.youtube.com/watch?v=SbLMmKs3gzw" found very slow( about 40~50K/s) at multiple test location (the network max speed is very high), how can I fix this issue?

best regards

**Comment by hk200** [comment]
test code appended
[VideoTest .java.txt](https://github.com/sealedtx/java-youtube-downloader/files/7356617/VideoTest.java.txt)

**Comment by hk200** [comment]
ok，many thanks, appreciated.I will check that. The speed of download was very high before and everything is ok, but something strange these days, every test point at different location is just 50~60k max download speed by now. I am very confused by this condition. I checked the code, network and hardware and seems found no odd by now.
did you run this code for test and get the high speed result by your side?
have been struggling this issue for several days.

best regards,

**Comment by hk200** [comment]
> @hk200 can you also check other formats, it might be problem only with DASH formats

ok, I check for this, many thanks.

**Comment by hk200** [comment]
> @hk200 hi, I looked through the code and your example and I can't see clearly what might cause such slow download speed. Investigation is required, you may start from looking at headers which are sent by browser and by youtube-downloader for same `Format.url()`

what is DASH format? and how can fix this format change to others at api?

**Comment by sealedtx** [comment]
@hk200 look at itags and comments: 
https://github.com/sealedtx/java-youtube-downloader/blob/70aeb61f1fe6fbc28a2dfd36f17ec6e2de46d21c/src/main/java/com/github/kiulian/downloader/model/videos/formats/Itag.java

**Comment by hk200** [comment]
> @hk200 look at itags and comments: https://github.com/sealedtx/java-youtube-downloader/blob/70aeb61f1fe6fbc28a2dfd36f17ec6e2de46d21c/src/main/java/com/github/kiulian/downloader/model/videos/formats/Itag.java

ok, many thanks. I try to change the format to fix this issue. the speed will be normal that we changed the DASH format, right? @sealedtx 

best regards,

**Comment by hk200** [comment]
we change and try all formats of testing video at different locations and cannot fix this issue.
@sealedtx need further help
best regards,
hk

**Comment by hk200** [comment]
> @hk200 what about issue in **youtube-dl**? is there any solution? it was mentioned that fork **yt-dlp** has implemented workaround, can you check it? if you can find it I may try implement it here

@sealedtx current issue I met is download video is very slow and I am not using y2-dl project.
someone metioned the similar y2 download throttling issue at other project has been fixed by one go-language based project.
https://github.com/89z/mech
but I am not go-language user, just use java language.

best regards,
hk

**Comment by hk200** [comment]
many thanks, we are blocked by this issue for many days.
@sealedtx 
and please open support donate platform like patreon.com/igorkiulian and I wanna do some support of our this project.
send it to me.
best regards,
hk

**Comment by sealedtx** [comment]
also may be useful for android spoofing
https://github.com/TeamNewPipe/NewPipeExtractor/issues/562

I cheked this endpoint, but I got 
```
<div style="margin-left: 4em;">
            <h1>We're sorry...</h1>
            <p>... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.</p>
</div>
```

Seems like Google protects this endpoint from being scrapped
